### ISSUE TITLE
Broken code due to changes in ignite

### ISSUE THREAD

**Issue by denizmsayin** [jrmcornish/cif#2]
Hello and first of all thank you for making all this great code available. I must say that I admire the scale at which you've made it both modular and easily configurable.
Sadly, however, I could not initially get the `main.py` script to work. After cloning the repository, updating the submodules and creating a conda env from the given `environment.yml` file, when I tried running the example command I got the following error:
```
(cif) deniz@prompt$ CUDA_VISIBLE_DEVICES=0 ./main.py --model resflow --dataset 2uniforms
Loading data...Done.
Did not find `latest' checkpoint.
Did not find `best_valid' checkpoint.

Config:
{
    "model": "resflow",
    "dataset": "2uniforms",
    "num_u_channels": 1,
    "use_cond_affine": true,
    "pure_cond_affine": false,
    "dequantize": false,
    "batch_norm": false,
    "act_norm": false,
    "max_epochs": 20000,
    "max_grad_norm": null,
    "early_stopping": true,
    "max_bad_valid_epochs": 20000,
    "train_batch_size": 1000,
    "valid_batch_size": 1000,
    "test_batch_size": 1000,
    "opt": "adam",
    "lr": 0.001,
    "lr_schedule": "none",
    "weight_decay": 0.0,
    "epochs_per_test": 5,
    "num_valid_elbo_samples": 10,
    "num_test_elbo_samples": 100,
    "schema_type": "flat-resflow",
    "num_density_layers": 10,
    "hidden_channels": [
        128,
        128,
        128,
        128
    ],
    "lipschitz_constant": 0.9,
    "max_train_lipschitz_iters": 5,
    "max_test_lipschitz_iters": 200,
    "lipschitz_tolerance": null,
    "reduce_memory": true,
    "st_nets": [
        10,
        10
    ],
    "p_nets": [
        10,
        10
    ],
    "q_nets": [
        10,
        10
    ],
    "should_checkpoint_best_valid": true,
    "should_checkpoint_latest": true,
    "write_to_disk": true,
    "data_root": "data/",
    "logdir_root": "runs/",
    "seed": 3863659876
}

Number of parameters: 506,830

Current run is terminating due to exception: When transformed engine's output is a mapping, it should contain ('y_pred', 'y') keys, but given ['metrics'].
Engine run is terminating due to exception: When transformed engine's output is a mapping, it should contain ('y_pred', 'y') keys, but given ['metrics'].
Traceback (most recent call last):
  File "./main.py", line 140, in <module>
    train(config=c, resume_dir=args.resume)
  File "/home/deniz/repos/cif/cif/experiment.py", line 40, in train
    trainer.train()
  File "/home/deniz/repos/cif/cif/trainer.py", line 152, in train
    self._trainer.run(data=self._train_loader, max_epochs=self._max_epochs)
  File "/home/deniz/anaconda3/envs/cif/lib/python3.8/site-packages/ignite/engine/engine.py", line 691, in run
    return self._internal_run()
  File "/home/deniz/anaconda3/envs/cif/lib/python3.8/site-packages/ignite/engine/engine.py", line 762, in _internal_run
    self._handle_exception(e)
  File "/home/deniz/anaconda3/envs/cif/lib/python3.8/site-packages/ignite/engine/engine.py", line 467, in _handle_exception
    raise e
  File "/home/deniz/anaconda3/envs/cif/lib/python3.8/site-packages/ignite/engine/engine.py", line 730, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "/home/deniz/anaconda3/envs/cif/lib/python3.8/site-packages/ignite/engine/engine.py", line 828, in _run_once_on_dataset
    self._handle_exception(e)
  File "/home/deniz/anaconda3/envs/cif/lib/python3.8/site-packages/ignite/engine/engine.py", line 467, in _handle_exception
    raise e
  File "/home/deniz/anaconda3/envs/cif/lib/python3.8/site-packages/ignite/engine/engine.py", line 812, in _run_once_on_dataset
    self._fire_event(Events.ITERATION_COMPLETED)
  File "/home/deniz/anaconda3/envs/cif/lib/python3.8/site-packages/ignite/engine/engine.py", line 423, in _fire_event
    func(*first, *(event_args + others), **kwargs)
  File "/home/deniz/anaconda3/envs/cif/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/deniz/anaconda3/envs/cif/lib/python3.8/site-packages/ignite/metrics/metric.py", line 278, in iteration_completed
    raise ValueError(
ValueError: When transformed engine's output is a mapping, it should contain ('y_pred', 'y') keys, but given ['metrics']
```
Although this error occurred with python 3.8, I also tried creating the environment with 3.7 and got the same error. I thought this might be due to version changes in ignite, and I tried forcing `ignite==0.3` in the `environment.yml` file (the most recent one which gets installed by default is 0.4.2 at the moment) and re-creating the environment, after which the code seems to be working fine. Perhaps setting the ignite version to the one you used during development would be a solution?

**Comment by jrmcornish** [comment]
Hi @denizmsayin - thanks very much for this and apologies for the delay in getting to this.

I've just put `ignite==0.3` like you suggest - that's what we were running when we did our experiments, so should be correct. I'll close this for now but do let us know if you have further problems :)
